version: '3.9'
services:
  init:
    tty: true
    stdin_open: true
    build:
      context: ./initial_sync
      args:
        WEBDAV_SERVER_ADDRESS: ${WEBDAV_SERVER_ADDRESS}
        KABU_PLUS_ID: ${KABU_PLUS_ID}
        KABU_PLUS_PW: ${KABU_PLUS_PW}
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse
    environment:
      - WEBDAV_SERVER_ADDRESS=${WEBDAV_SERVER_ADDRESS}
      - KABU_PLUS_ID=${KABU_PLUS_ID}
      - KABU_PLUS_PW=${KABU_PLUS_PW}
      - DIST=${DIST}
    volumes: 
      - ./csv:/opt/csv:delegated
      - ./initial_sync:/opt/sync

  daily:
    tty: true
    stdin_open: true
    build:
      context: ./daily_sync
      args:
        WEBDAV_SERVER_ADDRESS: ${WEBDAV_SERVER_ADDRESS}
        KABU_PLUS_ID: ${KABU_PLUS_ID}
        KABU_PLUS_PW: ${KABU_PLUS_PW}
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse
    environment:
      - WEBDAV_SERVER_ADDRESS=${WEBDAV_SERVER_ADDRESS}
      - KABU_PLUS_ID=${KABU_PLUS_ID}
      - KABU_PLUS_PW=${KABU_PLUS_PW}
      - DIST=${DIST}
      - OUTPUT_PATH=./current
    volumes: 
      - ./csv:/opt/csv:delegated
      - ./daily_sync/current:/opt/sync/current:delegated